================================================================================
ALTER USER moss WITH PASSWORD 'bestReceiver';
================================================================================
ALTER USER moss WITH PASSWORD 'bestReceiver';
--------------------------------------------------------------------------------
(source_file
    (alter_user
    (user
    (object_name))
    (user_password
    (string_literal))))