================================================================================
CREATE USER newuser WITH PASSWORD 'password';
================================================================================
CREATE USER newuser WITH PASSWORD 'password';
--------------------------------------------------------------------------------

(source_file
  (create_user
    (user)
    (user_password
      (string_literal))))
