================================================================================
CREATE TYPE cycling.basic_info (birthday timestamp, nationality text,  weight text,  height text);
================================================================================
CREATE TYPE cycling.basic_info (
  birthday timestamp,
  nationality text,
  weight text,
  height text
);
--------------------------------------------------------------------------------

(source_file
  (create_type
    (data_type_name)
    (data_type_name
      (object_name))
    (data_type_name
      (object_name))
    (data_type_name
      (object_name))))
