================================================================================
CREATE TYPE cycling.basic_info (birthday timestamp, nationality text,  weight text,  height text);
================================================================================
CREATE TYPE cycling.basic_info (
  birthday timestamp,
  nationality text,
  weight text,
  height text
);
--------------------------------------------------------------------------------
(source_file
    (create_type
    (keyspace
    (object_name))
    (type
    (object_name))
    (type_member_column_list
    (column
    (object_name))
    (data_type
    (data_type_name
    (object_name)))
    (column
    (object_name))
    (data_type
    (data_type_name
    (object_name)))
    (column
    (object_name))
    (data_type
    (data_type_name
    (object_name)))
    (column
    (object_name))
    (data_type
    (data_type_name
    (object_name))))))
