================================================================================
DROP MATERIALIZED VIEW cyclist_by_age;
================================================================================
DROP MATERIALIZED VIEW cyclist_by_age;
--------------------------------------------------------------------------------

(source_file
  (drop_materialized_view))

================================================================================
DROP MATERIALIZED VIEW cycling.cyclist_by_age;
================================================================================
DROP MATERIALIZED VIEW cycling.cyclist_by_age;
--------------------------------------------------------------------------------

(source_file
  (drop_materialized_view))

================================================================================
DROP MATERIALIZED VIEW if exists cyclist_by_age;
================================================================================
DROP MATERIALIZED VIEW if exists cyclist_by_age;
--------------------------------------------------------------------------------

(source_file
  (drop_materialized_view))

================================================================================
DROP MATERIALIZED VIEW if exists cycling.cyclist_by_age;
================================================================================
DROP MATERIALIZED VIEW if exists cycling.cyclist_by_age;
--------------------------------------------------------------------------------

(source_file
  (drop_materialized_view))
